[project]
name = "ix-watch"
version = "0.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.14, <3.15"
dependencies = [
    "apprise==1.9.6",
    "fastapi[standard]==0.125.0",
    "scapy==2.6.1",
]
